# Generated by Django 4.1.7 on 2023-03-24 10:53

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='زمان اپدیت')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت به ریال')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='زمان اپدیت')),
                ('name', models.CharField(max_length=20, verbose_name='نام محصول')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات محصول')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('finally_price', models.IntegerField(default=0, verbose_name='قیمت نهایی')),
                ('img', models.ImageField(upload_to='static/img/', verbose_name='عکس')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
