# Generated by Django 4.1.7 on 2023-03-24 10:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='توضیحات محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='finally_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='قیمت نهایی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='قیمت'),
        ),
    ]
