# Generated by Django 4.1.7 on 2023-03-26 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0005_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='زمان اپدیت')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('subject', models.CharField(max_length=50, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات محصول'),
        ),
    ]
