# Generated by Django 4.1.7 on 2023-04-01 17:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0007_alter_contactus_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='زمان اپدیت')),
                ('authority', models.CharField(max_length=40)),
                ('tracking_code', models.CharField(max_length=10, null=True, unique=True, verbose_name='کد پیگیری')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='onlineshop.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
