# Generated by Django 4.1.7 on 2023-04-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0008_alter_contactus_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='authority',
        ),
    ]
