# Generated by Django 4.1.7 on 2023-03-24 08:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=None, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
