# Generated by Django 4.0.1 on 2022-08-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='موضوع')),
                ('name', models.CharField(max_length=100, verbose_name='نام نویسنده')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('text', models.TextField(max_length=300, verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
